### ISSUE TITLE
Find a bug.

### ISSUE THREAD

**Issue by renyixin666** [QueuQ/CGLB#1]
I am interested in this benchmark. When looking through the code, there seems to be a code bug in GCGL/Baselines/mas_model?
https://github.com/QueuQ/CGLB/blob/966ba0e6a1ae5c0f6d0b4dd9d6f50e26200ab6f6/GCGL/Baselines/mas_model.py#L196-L197
If the moving average is calculated, it should be a multiplication operation here.

**Comment by b224618** [comment]
> I am interested in this benchmark. When looking through the code, there seems to be a code bug in GCGL/Baselines/mas_model?
> 
> https://github.com/QueuQ/CGLB/blob/966ba0e6a1ae5c0f6d0b4dd9d6f50e26200ab6f6/GCGL/Baselines/mas_model.py#L196-L197
> 
> 
> If the moving average is calculated, it should be a multiplication operation here.

Thanks a lot for pointing out this! we have corrected it and updated the repository. We will also re-run the corresponding experiments and update the results later.

**Comment by QueuQ** [comment]
> I am interested in this benchmark. When looking through the code, there seems to be a code bug in GCGL/Baselines/mas_model?
> 
> https://github.com/QueuQ/CGLB/blob/966ba0e6a1ae5c0f6d0b4dd9d6f50e26200ab6f6/GCGL/Baselines/mas_model.py#L196-L197
> 
> 
> If the moving average is calculated, it should be a multiplication operation here.

Thanks a lot for pointing out this, which is really helpful! We have corrected it and updated the repository. We will also re-run the experiments and update the results later in the repository!
