### ISSUE TITLE
 GCGL set_random seed is never called

### ISSUE THREAD

**Issue by WeiWeic6222848** [QueuQ/CGLB#12]
https://github.com/QueuQ/CGLB/blob/3e0debf02e582610d05274b44c4c09fc1c1fe4b2/GCGL/utils.py#L10

The function to set the random seed for GCGL is never executed, the reproducibility of the result is hindered.

**Comment by QueuQ** [comment]
> https://github.com/QueuQ/CGLB/blob/3e0debf02e582610d05274b44c4c09fc1c1fe4b2/GCGL/utils.py#L10
> 
> The function to set the random seed for GCGL is never executed, the reproducibility of the result is hindered.

Thanks for mentioning this point! We have enable the function to customize the random seed of the experiments.

https://github.com/QueuQ/CGLB/blob/f6628290b34c958ceff347c1b52c5138f3f1ef23/GCGL/train.py#L42-L43

https://github.com/QueuQ/CGLB/blob/f6628290b34c958ceff347c1b52c5138f3f1ef23/GCGL/train.py#L65-L66

Now the random seed can be set to either None or an integer
