### ISSUE TITLE
[Reproduce] Hyperparameters

### ISSUE THREAD

**Issue by doviettung96** [QueuQ/CGLB#2]
Dear @QueuQ ,
I find this work interesting and helpful for continual learning with graphs. According to the paper, the results from ERGNN is quite dominant. However, I can't reproduce your results with the default args. Thus, I would like to know the set of parameters that you used.
Thanks.

**Comment by doviettung96** [comment]
Ops. I found the hyperparameters in the Appendix.  Even though it lacks the number of training epochs for NGCL, I tried with 100 epochs and it seems to work. Thanks.

**Comment by QueuQ** [comment]
> 

Thanks for mentioning this issue, the default number of epochs is 200, I should have set it as 200 in the code, I have just updated it
