### ISSUE TITLE
Error occurred for jointtrain in GCGL

### ISSUE THREAD

**Issue by HyunjuKang** [QueuQ/CGLB#20]
in the line 470 in [CGLB](https://github.com/QueuQ/CGLB/tree/master)/[GCGL](https://github.com/QueuQ/CGLB/tree/master/GCGL)/pipeline.py, error occurred due to the wrong form of inputs

      for epoch in range(epochs):
            # Train
            if args['method'] == 'lwf':
                train_func(train_loader, loss_criterion, tid, args, prev_model)
            elif args['method'] == 'jointtrain':
                train_func(train_loader, loss_criterion, tid, args, train_loader_joint)
            else:
                train_func(train_loader, loss_criterion, tid, args)

The codes should be updated as below?

[1]
the function observe_tskIL_multicls in GCGL/Baselines/jointtrain_model.py
from def observe_tskIL_multicls(self, data_loader, loss_criterion, task_i, args, train_loader_joint):
-> to def observe_tskIL_multicls(self, train_loader_joint, loss_criterion, task_i, args):

And

[2]
in pipeline.py 
from train_func(train_loader, loss_criterion, tid, args, train_loader_joint)
-> to train_func(train_loader_joint, loss_criterion, tid, args)

**Comment by QueuQ** [comment]
> in the line 470 in [CGLB](https://github.com/QueuQ/CGLB/tree/master)/[GCGL](https://github.com/QueuQ/CGLB/tree/master/GCGL)/pipeline.py, error occurred due to the wrong form of inputs
> 
> ```
>   for epoch in range(epochs):
>         # Train
>         if args['method'] == 'lwf':
>             train_func(train_loader, loss_criterion, tid, args, prev_model)
>         elif args['method'] == 'jointtrain':
>             train_func(train_loader, loss_criterion, tid, args, train_loader_joint)
>         else:
>             train_func(train_loader, loss_criterion, tid, args)
> ```
> 
> The codes should be updated as below?
> 
> [1] the function observe_tskIL_multicls in GCGL/Baselines/jointtrain_model.py from def observe_tskIL_multicls(self, data_loader, loss_criterion, task_i, args, train_loader_joint): -> to def observe_tskIL_multicls(self, train_loader_joint, loss_criterion, task_i, args):
> 
> And
> 
> [2] in pipeline.py from train_func(train_loader, loss_criterion, tid, args, train_loader_joint) -> to train_func(train_loader_joint, loss_criterion, tid, args)

Hi, Thanks for your interest in our project!

Could please elaborate on what error did you meet, and what task was being run? We tested the code again, but the code for joint-training runs well, and we don't quite understand why the code should be modified as you suggested. Do you mean that the argument data_loader in observe_tskIL_multicls of jointtrain is not used, so it should be removed to make the code more concise?

**Comment by HyunjuKang** [comment]
The error was about the number of inputs in the argument.  The argument data_loader in observe_clsIL does (# of input is 4) not match with the train_func(train_loader, loss_criterion, tid, args, train_loader_joint). The original code should work in observe_tskIL_multicls of jointtrain as you mensioned but not the other two functions such as observe and observe_tskIL_multicls.

**Comment by QueuQ** [comment]
> The error was about the number of inputs in the argument. The argument data_loader in observe_clsIL does (# of input is 4) not match with the train_func(train_loader, loss_criterion, tid, args, train_loader_joint). The original code should work in observe_tskIL_multicls of jointtrain as you mensioned but not the other two functions such as observe and observe_tskIL_multicls.

Thanks for your further clarification! The code have been updated and the bug has been corrected. 

Please note that the train_loader_joint is only used for task-IL scenario in the multi-class situation, while for the class-IL scenario,  the train_loader for each task already contains all learnt task, which is realized in the class of GraphLevelDataset() in CGLB/GCGL/utils.py.

The reason of separately generating train_loader_joint  is because when generating the train_set for class-IL in CGLB/GCGL/utils.py, the test_set also contain all learnt tasks for each task, which is undesired for task-IL scenario.
