### ISSUE TITLE
Task identifier exposion in Class-IL setting.

### ISSUE THREAD

**Issue by Seven-Two** [QueuQ/CGLB#26]
Hi, it is known that the task identifier should be unknown to the model in the the class-IL setting, but in the code, it seems all the class-IL functions use the task identifier 't'. Could you please clarify this concern?

**Comment by QueuQ** [comment]
The t used in class-IL settings are not used to inform the model about the task identity of the given data. For example, if each task contains 2 classes, then after learning 3 tasks, the model has 6 activated prediction heads. The model needs to be set with 6 activated heads. But when the test data is given, the model does not know the task identity (e.g. whether the data belongs to the first two heads or the 5th and 6th head). Instead, the model has to pick one head out of the 6 existing heads. While in task-IL, the model will know the identity (e.g. the first two heads should be used, or the 3rd and 4th head should be used). This is the difference.
