### ISSUE TITLE
Redundant training in testing phase?

### ISSUE THREAD

**Issue by WeiWeic6222848** [QueuQ/CGLB#6]
In the following snippet, the model is first training for a user defined epoch, then overwritten by ```model = pickle.load(open(save_model_path,'rb')).cuda(args['gpu']) ``` if valid == False (which is the case for test phase). Does the training function still serves a purpose or is it redundant?

https://github.com/QueuQ/CGLB/blob/6d71034444031ce4aec5b1a4cbaefcddd6437f04/GCGL/pipeline.py#L370-L389

**Comment by QueuQ** [comment]
This actually does not incur redundant training, since 'epochs' is set as 0 when it is not training.
https://github.com/QueuQ/CGLB/blob/ed14a64283d642eadee7c31dda85886a4dbf1448/GCGL/pipeline.py#L312

**Comment by WeiWeic6222848** [comment]
thank you for clarifying this, sorry for missing the obvious variable change
