### ISSUE TITLE
Performance matrix visualization for GCGL is not working correctly

### ISSUE THREAD

**Issue by WeiWeic6222848** [QueuQ/CGLB#7]
Issue: Performance matrix visualization for GCGL tasks are all black, despite the acc being high.
Reason: The accuracy matrix for GCGL is not multiplied by 100, which is done for NCGL tasks.
https://github.com/QueuQ/CGLB/blob/6d71034444031ce4aec5b1a4cbaefcddd6437f04/GCGL/pipeline.py#L479
https://github.com/QueuQ/CGLB/blob/6d71034444031ce4aec5b1a4cbaefcddd6437f04/NCGL/pipeline.py#L527
Solution:
Add *100 for GCGL accuracies somewhere. I added this in the following line:
```acc_matrices.append(acc_matrix_test*100)```
https://github.com/QueuQ/CGLB/blob/6d71034444031ce4aec5b1a4cbaefcddd6437f04/GCGL/train.py#L153

**Comment by QueuQ** [comment]
Thanks for pointing out this, now we have added a multipler in the input arguments of the function show_performance_matrices in the visualize.py. When visualizing the values between 0 and 1, users can specify the multiplier as 100.
https://github.com/QueuQ/CGLB/blob/ed14a64283d642eadee7c31dda85886a4dbf1448/NCGL/visualize.py#L40-L53

**Comment by WeiWeic6222848** [comment]
thank you
